// lấy danh sách rap
// export const GET_CINEMA_SYSTEM = "GET_CINEMA_SYSTEM";
export const GET_CINEMA_SYSTEM_SUCCESS = "GET_CINEMA_SYSTEM_SUCCESS";
export const GET_CINEMA_SYSTEM_FAILED = "GET_CINEMA_SYSTEM_FAILED";

// lấy thông tin hệ thống rạp
// export const GET_CINEMA_SYSTEM_INFO = "GET_CINEMA_SYSTEM_INFO";
export const GET_CINEMA_SYSTEM_INFO_SUCCESS = "GET_CINEMA_SYSTEM_INFO_SUCCESS";
export const GET_CINEMA_SYSTEM_INFO_FAILED = "GET_CINEMA_SYSTEM_INFO_FAILED";

// lấy thông tin lịch chiếu hệ thống Rạp
export const GET_CINEMA_SYSTEM_SHOWTIME_SUCCESS =
  "GET_CINEMA_SYSTEM_SHOWTIME_SUCCESS";
export const GET_CINEMA_SYSTEM_SHOWTIME_FAILED =
  "GET_CINEMA_SYSTEM_SHOWTIME_FAILED";
