export const GET_CINEMA_SYSTEM = "GET_CINEMA_SYSTEM";
export const GET_CINEMA_SYSTEM_SUCCESS = "GET_CINEMA_SYSTEM_SUCCESS";
export const GET_CINEMA_SYSTEM_FAILED = "GET_CINEMA_SYSTEM_FAILED";

export const GET_CINEMA_SYSTEM_INFO = "GET_CINEMA_SYSTEM_INFO";
export const GET_CINEMA_SYSTEM_INFO_SUCCESS = "GET_CINEMA_SYSTEM_INFO_SUCCESS";
export const GET_CINEMA_SYSTEM_INFO_FAILED = "GET_CINEMA_SYSTEM_INFO_FAILED";
