export const GET_MOVIE_LIST = "GET_MOVIE_LIST";
export const GET_MOVIE_LIST_SUCCESS = "GET_MOVIE_LIST_SUCCESS";
export const GET_MOVIE_LIST_FAILED = "GET_MOVIE_LIST_FAILED";

export const GET_MOVIE_LIST_PANIGATION = "GET_MOVIE_LIST_PANIGATION";
export const GET_MOVIE_LIST_PANIGATION_SUCCESS =
  "GET_MOVIE_LIST_PANIGATION_SUCCESS";
export const GET_MOVIE_LIST_PANIGATION_FAILED =
  "GET_MOVIE_LIST_PANIGATION_FAILED";

export const GET_MOVIE_DETAIL = "GET_MOVIE_DETAIL";
export const GET_MOVIE_DETAIL_SUCCESS = "GET_MOVIE_DETAIL_SUCCESS";
export const GET_MOVIE_DETAIL_FAILED = "GET_MOVIE_DETAIL_FAILED";

// tìm kiếm movie theo tên
export const GET_MOVIE_LIST_BY_NAME_SUCCESS = "GET_MOVIE_LIST_BY_NAME_SUCCESS";
export const GET_MOVIE_LIST_BY_NAME_FAILED = "GET_MOVIE_LIST_BY_NAME_FAILED";
