// lấy danh sách phim
// export const GET_MOVIE_LIST = "GET_MOVIE_LIST";
export const GET_MOVIE_LIST_SUCCESS = "GET_MOVIE_LIST_SUCCESS";
export const GET_MOVIE_LIST_FAILED = "GET_MOVIE_LIST_FAILED";

// lấy danh sách phim phân trang
// export const GET_MOVIE_LIST_PANIGATION = "GET_MOVIE_LIST_PANIGATION";
export const GET_MOVIE_LIST_PANIGATION_SUCCESS =
  "GET_MOVIE_LIST_PANIGATION_SUCCESS";
export const GET_MOVIE_LIST_PANIGATION_FAILED =
  "GET_MOVIE_LIST_PANIGATION_FAILED";

// lấy chi tiết phim theo mã phim
// export const GET_MOVIE_DETAIL = "GET_MOVIE_DETAIL";
export const GET_MOVIE_DETAIL_SUCCESS = "GET_MOVIE_DETAIL_SUCCESS";
export const GET_MOVIE_DETAIL_FAILED = "GET_MOVIE_DETAIL_FAILED";

// tìm kiếm movie theo tên
export const GET_MOVIE_LIST_BY_NAME_SUCCESS = "GET_MOVIE_LIST_BY_NAME_SUCCESS";
export const GET_MOVIE_LIST_BY_NAME_FAILED = "GET_MOVIE_LIST_BY_NAME_FAILED";

//thêm phim
export const ADD_MOVIE_SUCCESS = "ADD_MOVIE_SUCCESS";
export const ADD_MOVIE_FAILED = "ADD_MOVIE_FAILED";

// xóa phim
export const DELETE_MOVIE_SUCCESS = "DELETE_MOVIE_SUCCESS";
export const DELETE_MOVIE_FAILED = "DELETE_MOVIE_FAILED";
